<a href="https://colab.research.google.com/github/rajatiitm/Deep-Learning-Models/blob/master/Linear_Regression_using_torch_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch.nn as nn
import torch
import numpy as np

In [23]:
inp = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')
tar = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')
inp=torch.from_numpy(inp)
tar=torch.from_numpy(tar)

In [24]:
from torch.utils.data import TensorDataset   #Tensorset allows access to rows from inp and targets as tuples
#also provides standard API for working on different datasets on pytorch

In [25]:
train_ds= TensorDataset(inp,tar)


In [26]:
train_ds

In [27]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [28]:
from torch.utils.data import DataLoader

In [29]:
#define data loader
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [30]:
for x,y in train_dl:     #if shuffle is set to true then the dataloader shuffles the data b4 creating batches
    print(x)
    print(y)
    break

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 22.,  37.]])


In [31]:
model=nn.Linear(3,2)


In [32]:
model.weight

Parameter containing:
tensor([[-0.1532,  0.4937, -0.3168],
        [-0.5207,  0.0965,  0.1774]], requires_grad=True)

In [33]:
model.bias

Parameter containing:
tensor([-0.4784, -0.2858], requires_grad=True)

In [34]:
pred=model(inp)

In [35]:
#Loss Function
import torch.nn.functional as F

In [36]:
loss_fn=F.mse_loss

In [37]:
#Optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)  #lr is for the learning rate at which the values of weights and biases work.


In [38]:
#Train the model
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for x,y in train_dl:
            pred=model(x)
            loss=loss_fn(pred,y)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10 == 0:
           print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))     

In [39]:
fit(10000,model,loss_fn,opt,train_dl)

Epoch [10/10000], Loss: 187.4111
Epoch [20/10000], Loss: 94.3853
Epoch [30/10000], Loss: 39.8336
Epoch [40/10000], Loss: 35.2528
Epoch [50/10000], Loss: 44.4187
Epoch [60/10000], Loss: 73.1933
Epoch [70/10000], Loss: 53.1931
Epoch [80/10000], Loss: 46.8144
Epoch [90/10000], Loss: 19.6459
Epoch [100/10000], Loss: 25.3503
Epoch [110/10000], Loss: 37.9262
Epoch [120/10000], Loss: 32.4780
Epoch [130/10000], Loss: 25.2905
Epoch [140/10000], Loss: 9.7080
Epoch [150/10000], Loss: 12.8801
Epoch [160/10000], Loss: 22.2999
Epoch [170/10000], Loss: 13.8534
Epoch [180/10000], Loss: 15.2669
Epoch [190/10000], Loss: 20.8429
Epoch [200/10000], Loss: 12.0683
Epoch [210/10000], Loss: 17.3562
Epoch [220/10000], Loss: 6.4068
Epoch [230/10000], Loss: 1.5377
Epoch [240/10000], Loss: 5.8807
Epoch [250/10000], Loss: 14.3875
Epoch [260/10000], Loss: 9.5122
Epoch [270/10000], Loss: 12.4316
Epoch [280/10000], Loss: 17.5529
Epoch [290/10000], Loss: 5.9275
Epoch [300/10000], Loss: 9.8590
Epoch [310/10000], Loss: 